apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wyyeureb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-wyyeureb:a2c27defd9d7d323ff5a738f95dafbc85e18b845@sha256:4d29024a8a0fb6e437baec3cc36dd00a4e6286ee51f21ded17fc2c472e8c7fda
          name: container-image
